[pytest]
asyncio_mode = auto
timeout = 300
filterwarnings =
    ignore::DeprecationWarning:transformers.*
    ignore::UserWarning:torch.*
    ignore::FutureWarning:huggingface_hub.*
    ignore::pydantic.warnings.PydanticDeprecatedSince20
    ignore::pydantic.PydanticDeprecatedSince20
log_cli = false
log_cli_level = WARNING