"""add model PairPriceMetrics

Revision ID: 1e5fe789c285
Revises: b6d7654d44a5
Create Date: 2026-05-05 09:50:22.681549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e5fe789c285'
down_revision: Union[str, Sequence[str], None] = 'b6d7654d44a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pair_price_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('price_segment', sa.String(), nullable=False),
    sa.Column('pair_id', sa.Integer(), nullable=False),
    sa.Column('our_pharmacy', sa.String(), nullable=False),
    sa.Column('competitor_pharmacy', sa.String(), nullable=False),
    sa.Column('our_price', sa.Numeric(), nullable=False),
    sa.Column('competitor_price', sa.Numeric(), nullable=False),
    sa.Column('diff_abs', sa.Numeric(), nullable=False),
    sa.Column('diff_pct', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pair_price_metrics_city'), 'pair_price_metrics', ['city'], unique=False)
    op.create_index(op.f('ix_pair_price_metrics_import_id'), 'pair_price_metrics', ['import_id'], unique=False)
    op.create_index(op.f('ix_pair_price_metrics_pair_id'), 'pair_price_metrics', ['pair_id'], unique=False)
    op.create_index(op.f('ix_pair_price_metrics_price_segment'), 'pair_price_metrics', ['price_segment'], unique=False)
    op.create_index(op.f('ix_pair_price_metrics_product_name'), 'pair_price_metrics', ['product_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pair_price_metrics_product_name'), table_name='pair_price_metrics')
    op.drop_index(op.f('ix_pair_price_metrics_price_segment'), table_name='pair_price_metrics')
    op.drop_index(op.f('ix_pair_price_metrics_pair_id'), table_name='pair_price_metrics')
    op.drop_index(op.f('ix_pair_price_metrics_import_id'), table_name='pair_price_metrics')
    op.drop_index(op.f('ix_pair_price_metrics_city'), table_name='pair_price_metrics')
    op.drop_table('pair_price_metrics')
    # ### end Alembic commands ###
