"""add price_segment in normalized price

Revision ID: 31f20f06f595
Revises: 7bded30d838c
Create Date: 2026-04-29 16:19:38.619011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f20f06f595'
down_revision: Union[str, Sequence[str], None] = '7bded30d838c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('normalized_prices', sa.Column('price_segment', sa.String(), nullable=True))
    op.create_index(op.f('ix_normalized_prices_price_segment'), 'normalized_prices', ['price_segment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_normalized_prices_price_segment'), table_name='normalized_prices')
    op.drop_column('normalized_prices', 'price_segment')
    # ### end Alembic commands ###
