"""upgrade tablbes new

Revision ID: 3cc5a7c25223
Revises: efdb14512983
Create Date: 2026-05-07 14:53:00.565541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc5a7c25223'
down_revision: Union[str, Sequence[str], None] = 'efdb14512983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitor_metrics', sa.Column('pharmacy_instance', sa.String(), nullable=False))
    op.create_index(op.f('ix_competitor_metrics_pharmacy_instance'), 'competitor_metrics', ['pharmacy_instance'], unique=False)
    op.add_column('normalized_prices', sa.Column('pharmacy_instance', sa.String(), nullable=False))
    op.create_index(op.f('ix_normalized_prices_pharmacy_instance'), 'normalized_prices', ['pharmacy_instance'], unique=False)
    op.add_column('pair_price_metrics', sa.Column('our_pharmacy_name', sa.String(), nullable=False))
    op.add_column('pair_price_metrics', sa.Column('our_pharmacy_instance', sa.String(), nullable=False))
    op.add_column('pair_price_metrics', sa.Column('competitor_pharmacy_name', sa.String(), nullable=False))
    op.add_column('pair_price_metrics', sa.Column('competitor_pharmacy_instance', sa.String(), nullable=False))
    op.drop_column('pair_price_metrics', 'our_pharmacy')
    op.drop_column('pair_price_metrics', 'competitor_pharmacy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pair_price_metrics', sa.Column('competitor_pharmacy', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('pair_price_metrics', sa.Column('our_pharmacy', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('pair_price_metrics', 'competitor_pharmacy_instance')
    op.drop_column('pair_price_metrics', 'competitor_pharmacy_name')
    op.drop_column('pair_price_metrics', 'our_pharmacy_instance')
    op.drop_column('pair_price_metrics', 'our_pharmacy_name')
    op.drop_index(op.f('ix_normalized_prices_pharmacy_instance'), table_name='normalized_prices')
    op.drop_column('normalized_prices', 'pharmacy_instance')
    op.drop_index(op.f('ix_competitor_metrics_pharmacy_instance'), table_name='competitor_metrics')
    op.drop_column('competitor_metrics', 'pharmacy_instance')
    # ### end Alembic commands ###
