"""add price_segment in LLMReport

Revision ID: 64983bc519ba
Revises: 1e5fe789c285
Create Date: 2026-05-07 09:01:10.068479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64983bc519ba'
down_revision: Union[str, Sequence[str], None] = '1e5fe789c285'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_reports', sa.Column('price_segment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_reports', 'price_segment')
    # ### end Alembic commands ###
