"""add models for competitor_analysis

Revision ID: 7bded30d838c
Revises: c37c0642a0e2
Create Date: 2026-04-22 20:46:33.553373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bded30d838c'
down_revision: Union[str, Sequence[str], None] = 'c37c0642a0e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('excel', 'onec', 'api', name='sourcetype'), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('uploaded', 'processing', 'done', 'error', name='importstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('city_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('avg_price', sa.Numeric(), nullable=False),
    sa.Column('price_dispersion', sa.Numeric(), nullable=False),
    sa.Column('avg_discount', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_city_metrics_city'), 'city_metrics', ['city'], unique=False)
    op.create_index(op.f('ix_city_metrics_import_id'), 'city_metrics', ['import_id'], unique=False)
    op.create_table('competitor_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('pharmacy_name', sa.String(), nullable=False),
    sa.Column('price_index', sa.Numeric(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitor_metrics_city'), 'competitor_metrics', ['city'], unique=False)
    op.create_index(op.f('ix_competitor_metrics_import_id'), 'competitor_metrics', ['import_id'], unique=False)
    op.create_index(op.f('ix_competitor_metrics_pharmacy_name'), 'competitor_metrics', ['pharmacy_name'], unique=False)
    op.create_table('llm_reports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_reports_import_id'), 'llm_reports', ['import_id'], unique=False)
    op.create_table('normalized_prices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('pharmacy_name', sa.String(), nullable=False),
    sa.Column('is_our', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_prices_city'), 'normalized_prices', ['city'], unique=False)
    op.create_index(op.f('ix_normalized_prices_import_id'), 'normalized_prices', ['import_id'], unique=False)
    op.create_index(op.f('ix_normalized_prices_pharmacy_name'), 'normalized_prices', ['pharmacy_name'], unique=False)
    op.create_index(op.f('ix_normalized_prices_product_name'), 'normalized_prices', ['product_name'], unique=False)
    op.create_table('product_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('avg_price', sa.Numeric(), nullable=False),
    sa.Column('min_price', sa.Numeric(), nullable=False),
    sa.Column('max_price', sa.Numeric(), nullable=False),
    sa.Column('std_dev', sa.Numeric(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_metrics_city'), 'product_metrics', ['city'], unique=False)
    op.create_index(op.f('ix_product_metrics_import_id'), 'product_metrics', ['import_id'], unique=False)
    op.create_index(op.f('ix_product_metrics_product_name'), 'product_metrics', ['product_name'], unique=False)
    op.create_table('raw_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('sheet_name', sa.String(), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_data')
    op.drop_index(op.f('ix_product_metrics_product_name'), table_name='product_metrics')
    op.drop_index(op.f('ix_product_metrics_import_id'), table_name='product_metrics')
    op.drop_index(op.f('ix_product_metrics_city'), table_name='product_metrics')
    op.drop_table('product_metrics')
    op.drop_index(op.f('ix_normalized_prices_product_name'), table_name='normalized_prices')
    op.drop_index(op.f('ix_normalized_prices_pharmacy_name'), table_name='normalized_prices')
    op.drop_index(op.f('ix_normalized_prices_import_id'), table_name='normalized_prices')
    op.drop_index(op.f('ix_normalized_prices_city'), table_name='normalized_prices')
    op.drop_table('normalized_prices')
    op.drop_index(op.f('ix_llm_reports_import_id'), table_name='llm_reports')
    op.drop_table('llm_reports')
    op.drop_index(op.f('ix_competitor_metrics_pharmacy_name'), table_name='competitor_metrics')
    op.drop_index(op.f('ix_competitor_metrics_import_id'), table_name='competitor_metrics')
    op.drop_index(op.f('ix_competitor_metrics_city'), table_name='competitor_metrics')
    op.drop_table('competitor_metrics')
    op.drop_index(op.f('ix_city_metrics_import_id'), table_name='city_metrics')
    op.drop_index(op.f('ix_city_metrics_city'), table_name='city_metrics')
    op.drop_table('city_metrics')
    op.drop_table('imports')
    # ### end Alembic commands ###
