"""add price_segment in models

Revision ID: 947486d1e7e8
Revises: 31f20f06f595
Create Date: 2026-04-29 19:38:30.135077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947486d1e7e8'
down_revision: Union[str, Sequence[str], None] = '31f20f06f595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city_metrics', sa.Column('price_segment', sa.String(), nullable=True))
    op.create_index(op.f('ix_city_metrics_price_segment'), 'city_metrics', ['price_segment'], unique=False)
    op.add_column('competitor_metrics', sa.Column('price_segment', sa.String(), nullable=True))
    op.create_index(op.f('ix_competitor_metrics_price_segment'), 'competitor_metrics', ['price_segment'], unique=False)
    op.add_column('product_metrics', sa.Column('price_segment', sa.String(), nullable=True))
    op.create_index(op.f('ix_product_metrics_price_segment'), 'product_metrics', ['price_segment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_metrics_price_segment'), table_name='product_metrics')
    op.drop_column('product_metrics', 'price_segment')
    op.drop_index(op.f('ix_competitor_metrics_price_segment'), table_name='competitor_metrics')
    op.drop_column('competitor_metrics', 'price_segment')
    op.drop_index(op.f('ix_city_metrics_price_segment'), table_name='city_metrics')
    op.drop_column('city_metrics', 'price_segment')
    # ### end Alembic commands ###
