"""add pair competitor for NormalizedPrice

Revision ID: b6d7654d44a5
Revises: 947486d1e7e8
Create Date: 2026-05-05 08:58:27.192470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6d7654d44a5'
down_revision: Union[str, Sequence[str], None] = '947486d1e7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('normalized_prices', sa.Column('pair_id', sa.Integer(), nullable=False))
    op.add_column('normalized_prices', sa.Column('competitor_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_normalized_prices_pair_id'), 'normalized_prices', ['pair_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_normalized_prices_pair_id'), table_name='normalized_prices')
    op.drop_column('normalized_prices', 'competitor_name')
    op.drop_column('normalized_prices', 'pair_id')
    # ### end Alembic commands ###
